FROM golang:1.16

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

ENV REQUEST_ORIGIN=http://frontend-server:3000

RUN go build -o server

RUN test ./...

EXPOSE 8080

CMD [ "./server" ]
