version: '3.5'

services:
  frontend-server:
    build: ./example-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://backend-server:8080
    ports:
      - 3000:3000
  
  backend-server:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://frontend-server:3000
      - REDIS_HOST=myredis
  myredis:
    image: redis:latest
